#!/usr/bin/env bash

echo "Checking for dependencies..."
declare -a needed
if ! command -v nvim &> /dev/null; then
	needed+=("nvim")
fi

if ! command -v tmux &> /dev/null; then
	needed+=("tmux")
fi

if ! command -v git &> /dev/null; then
	needed+=("git")
fi

if [ ${#needed[@]} -ne 0 ]; then
	echo "needed = ${#needed[@]}"
	echo -e "\nBefore proceeding with this script, please install the following dependencies:"
	for f in ${needed[@]}; do
		echo "$f"
	done
	exit
else
	echo -e "\nFound all required dependencies!"
fi

echo -e "\nThe execution of this script will remove the following files/directories on "
echo "your local system: "
echo -e "\t.bashrc\n\t.bash_aliases\n\t.config/git/\n\t.tmux.conf\n\t.config/nvim/"
echo -e "\nConfirm? [y/n]"
read user_response
if [ $user_response == 'n' ]; then
	echo -e "\nScript cancelled."
	exit
else
	echo -e "\nConfiguring symlinks"
fi

BASEDIR=$(dirname $0)
cd $BASEDIR

# Clean start
if ! [ -d ~/.config ]; then
	mkdir -v ~/.config
fi

rm -vrf ~/.bash_aliases ~/.bashrc ~/.tmux.conf ~/.config/git ~/.config/nvim

# Files
ln -s ${PWD}/aliases ~/.bash_aliases
ln -s ${PWD}/bashrc ~/.bashrc
ln -s ${PWD}/tmux.conf ~/.tmux.conf

# Directories
ln -s -t ~/.config/ ${PWD}/git
ln -s -t ~/.config/ ${PWD}/nvim
