#!/usr/bin/env bash

# Colors
g="\e[32m"
r="\e[31m"
b="\e[1m"
d="\e[39m\e[0m"

echo -e "Checking for dependencies..."
declare -a needed
if ! command -v nvim &> /dev/null; then
	needed+=("nvim")
fi

if ! command -v pandoc &> /dev/null; then
	needed+=("pandoc")
fi

if ! command -v tmux &> /dev/null; then
	needed+=("tmux")
fi

if ! command -v git &> /dev/null; then
	needed+=("git")
fi

if [ ${#needed[@]} -ne 0 ]; then
	echo -e "\nBefore proceeding with this script, please install the following dependencies:"
	for f in ${needed[@]}; do
		echo -e "\t${r}$f${d}"
	done
	exit
else
	echo -e "\n${g}Found all required dependencies!${d}"
fi

echo -e "\nThe execution of this script will remove the following files/directories on "
echo "your local system: "
echo -e "\t.bashrc\n\t.bash_aliases\n\t.config/git/\n\t.tmux.conf\n\t.config/nvim/"
echo -e "\nConfirm? [y/n]"
read user_response
if ! [ $user_response == 'y' ]; then
	echo -e "\n${r}Script cancelled.${d}"
	exit
fi

BASEDIR=$(dirname $0)
cd $BASEDIR

# Clean start
if ! [ -d ~/.config ]; then
	mkdir -v ~/.config
fi

echo -e "\nRemoving existing files/directories..."
echo -e "--------------------------------------"
rm -vrf ~/.bash_aliases ~/.bashrc ~/.tmux.conf ~/.config/git ~/.config/nvim ~/.config/gnu-readline.conf
echo -e "\nConfiguring symlinks"
echo -e "--------------------"

# Files
ln -sv ${PWD}/aliases ~/.bash_aliases
ln -sv ${PWD}/bashrc ~/.bashrc
ln -sv ${PWD}/tmux.conf ~/.tmux.conf
ln -sv ${PWD}/gnu-readline.conf ~/.config/gnu-readline.conf

# Directories
ln -sv -t ~/.config/ ${PWD}/git
ln -sv -t ~/.config/ ${PWD}/nvim

echo -e "\n${g}Complete.${d}"
